In [3]:
import numpy as np
import pandas as pd

In [4]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### Create Data Frame

In [5]:
df = pd.DataFrame(data=np.arange(0,20).reshape(5,4), index=["Row1", "Row2","Row3","Row4","Row5"],columns=["Column1", "Column2","Column3","Column4"])


In [6]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [7]:
df.head()
df.head(2)

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [8]:
df.tail()
df.tail(2)

Column1  Column2  Column3  Column4
Row4       12       13       14       15
Row5       16       17       18       19

In [9]:
type(df) ## DataFrame - > a type of data structure

pandas.core.frame.DataFrame

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [11]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

### Indexing
- Direct Using By Column Name
- rowindex[loc]
- Row Index Column Index Number[.iloc] : .iloc -> Index Location

In [12]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [13]:
df[['Column1','Column2','Column3']]

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [14]:
# By using Column1 Name
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int64

In [15]:
type(df[['Column1','Column2','Column3']])

pandas.core.frame.DataFrame

In [16]:
type(df['Column1'])


pandas.core.series.Series

In [17]:
#when we are adding multiple rows and coloumn are called data frame

In [18]:
df.loc['Row3']

Column1     8
Column2     9
Column3    10
Column4    11
Name: Row3, dtype: int64

In [19]:
type(df.loc['Row3'])


pandas.core.series.Series

In [20]:
# using row index name by loc
type(df.loc[['Row1','Row2','Row3']])


pandas.core.frame.DataFrame

In [21]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [22]:
df.iloc[2:4,:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [23]:
df.head()


Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [24]:
df.iloc[1:3,1:3]

Column2  Column3
Row2        5        6
Row3        9       10

In [25]:
df.iloc[2:4,1:3]

Column2  Column3
Row3        9       10
Row4       13       14

In [26]:
# Assingment

# 1) Rows
# Row1 - Row5

df.iloc[:,0:1]

# 2) Columns
# Row1 - Row5

df.iloc[:,3:]

Column4
Row1        3
Row2        7
Row3       11
Row4       15
Row5       19

In [27]:
# to convert data Frames to Arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

### Basic Operations

In [28]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [29]:
 df.isnull()

Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False

In [30]:
 df.isnull().sum()


Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [31]:
df = pd.DataFrame(data=[[1,np.nan,2 ], [1,3,4]] ,index=["Row1", "Row2"],columns=["Column1", "Column2","Column3"])
# np.nan => null value 


In [32]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [33]:
df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False

In [34]:
df.isnull().sum()
df.isnull().sum()==0

Column1     True
Column2    False
Column3     True
dtype: bool

In [35]:
df['Column3'].value_counts()

2    1
4    1
Name: Column3, dtype: int64

In [36]:
df = pd.DataFrame(data=np.arange(0,20).reshape(5,4), index=["Row1", "Row2","Row3","Row4","Row5"],columns=["Column1", "Column2","Column3","Column4"])
df


Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [37]:
df['Column3'].value_counts()


2     1
6     1
10    1
14    1
18    1
Name: Column3, dtype: int64

In [38]:
df = pd.DataFrame(data=[[1,np.nan,2 ], [1,3,2],  [3,5,6]] ,index=["Row1", "Row2","Row3"],columns=["Column1", "Column2","Column3"])
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        2
Row3        3      5.0        6

In [39]:
df[['Column1','Column3']].value_counts()


Column1  Column3
1        2          2
3        6          1
dtype: int64

In [40]:
df['Column3'].unique()

array([2, 6])

In [41]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        2
Row3        3      5.0        6

In [43]:
df>2



Column1  Column2  Column3
Row1    False    False    False
Row2    False     True    False
Row3     True     True     True

In [44]:
df['Column2']>2

Row1    False
Row2     True
Row3     True
Name: Column2, dtype: bool

In [45]:
# Conditioning Indexing
df[df['Column2']>2]
df[df['Column2']>2 and ['Column2']>2]

Column1  Column2  Column3
Row2        1      3.0        2
Row3        3      5.0        6