In [8]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4], 
              [5,6,7,8]])
a.shape

(2, 4)

In [9]:
b = np.array([[1,2,3,4], [5,6,7,8],
               [9,10,11,12],[13,14,15,16]])

b.shape

b[0] = 10

b

array([[10, 10, 10, 10],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
c = np.array([1,2,3,4,5,6,7,8,9])
# c[-5:-2]
c[:3]

array([1, 2, 3])

In [19]:
a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

a[1, 2]

7

In [21]:
# ndim (Number of Dimensions)
a.ndim
a.shape

(3, 4)

In [18]:
ar = np.array([1,2,3,4,5])
ar.shape

len(ar.shape)



1

In [23]:
ar.dtype
b = np.array(['Name','email','class'])

b.dtype

dtype('<U5')

In [31]:
a = np.zeros((4,4))
a

b = np.ones((5,6))
b

c = np.empty((2,4))
c

d = np.zeros(5)
d

array([0., 0., 0., 0., 0.])

In [38]:
# np.arange(5)
np.arange(0, 10)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [44]:
np.linspace(1, 5, num=9)


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [46]:
sorting = np.array([5,6,2,7,9,1,8,4,3])
np.sort(sorting)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a.size

8

In [63]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example.ndim
array_example.size

array_example.shape

(3, 2, 4)

In [73]:
a = np.arange(9)
a

b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
a = np.array([1, 2, 3, 4, 5, 6])
a.ndim

1

In [ ]:
a2 = a[np.newaxis, :]
#newaxis add new axis and row, : -> saare elelments lelo as it s
a2

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
row_vector = a[np.newaxis, :] #row
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [98]:
colm_vector = a[:, np.newaxis] #column
colm_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [103]:
data = np.array([1,2,3])
data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [111]:
a = np.arange(10)
a[a < 9]
# b = a[a >= 5]
# b = b + 1
# b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [113]:
a = np.arange(10)
a[a < 9]
b = a[a >= 5]
b = b + 1
b

array([ 6,  7,  8,  9, 10])

In [114]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [117]:
np.nonzero(a < 5)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [119]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [121]:
a1 = np.array([[1,2],
               [3,4]])
a2 = np.array([[5,6],
               [7,8]])

np.vstack((a1,a2))
np.hstack((a1,a2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [128]:
x = np.arange(1, 25).reshape(2,12)
x


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [130]:
np.hsplit(x,3)
np.hsplit(x,(3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [132]:
a = np.array([1,2,3,4,5])
b = a.copy()
b

array([1, 2, 3, 4, 5])

In [143]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)# by default 1..
ones

array([1, 1])

In [144]:
data + ones

array([2, 3])

In [146]:
a = np.array([1,2,3,4,5])
a.sum()

15

In [ ]:
b = np.array([[1, 1], [2, 2]])
b.sum()    

6

In [150]:
b.sum(axis=1)

array([2, 4])

In [154]:
data = np.array([1.0, 2.0, 3.0, 6.3])
data * 1.6

array([ 1.6 ,  3.2 ,  4.8 , 10.08])

In [160]:
a = np.array([1 ,2, 3, 4, 5, 6, 7, 8])
a.max()
a.min()
a.sum()

36

In [162]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

a.sum()
a.min()

0.05093587

In [165]:
data = np.array([[1,2], [3,4], [5,6]])
ones_row = np.array([[1, 1]])
ones_row + data

array([[2, 3],
       [4, 5],
       [6, 7]])

In [167]:
np.random.random(4)
np.random.random((4, 3))

array([[0.06275172, 0.34494489, 0.21735085],
       [0.85559038, 0.05764914, 0.19211757],
       [0.77602538, 0.94329421, 0.40065719],
       [0.6251585 , 0.22990256, 0.96150558]])