### Revision

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
# print(arr)

arr2 = np.array(([1,2,3],[4,5,6],[7,8,9]))
# print(arr2,"\n")

# for i in arr2:
#     print(i)

# print("\nSqare of arr: \n", arr2 * 2)

transposeArray = arr2.T
# print(transposeArray)


zeroArray = np.zeros([3,3])
print(zeroArray, "\n")

onesArray = np.ones((3,3))
print(onesArray)

# twoArray = np.trace()
# print(twoArray)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
